<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Valyze.Infraestructure.Repository</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Valyze.Domain\Valyze.Domain.csproj" />
    <ProjectReference Include="..\Valyze.Infraestructure.EntityFramework\Valyze.Infraestructure.EntityFramework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
