// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valyze.Infraestructure.EntityFramework;

#nullable disable

namespace Valyze.Infraestructure.EntityFramework.Migrations
{
    [DbContext(typeof(ValyzeDbContext))]
    [Migration("20260506205539_AddInvestmentDecisionsTable")]
    partial class AddInvestmentDecisionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.InvestmentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<Guid?>("AiChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_chat_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EvaluationHorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_horizon_days");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<Guid?>("LinkedTradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_trade_id");

                    b.Property<decimal?>("PriceAtDecisionAmount")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("price_at_decision_amount");

                    b.Property<string>("PriceAtDecisionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_at_decision_currency");

                    b.Property<decimal?>("QuantityAmount")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("quantity_amount");

                    b.Property<string>("QuantityCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quantity_currency");

                    b.Property<short>("QuantityUnits")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity_units");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("SourceOtherNote")
                        .HasColumnType("text")
                        .HasColumnName("source_other_note");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTradeId")
                        .HasDatabaseName("ix_investment_decisions_linked_trade_id")
                        .HasFilter("\"linked_trade_id\" IS NOT NULL");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_investment_decisions_account_created_at");

                    b.HasIndex("AccountId", "Isin")
                        .HasDatabaseName("ix_investment_decisions_account_isin")
                        .HasFilter("\"isin\" IS NOT NULL");

                    b.HasIndex("AccountId", "Source", "Action", "CreatedAt")
                        .HasDatabaseName("ix_investment_decisions_account_source_action_created_at");

                    b.ToTable("investment_decisions", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_news_articles_published_at");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_news_articles_source_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_news_articles_url_unique");

                    b.ToTable("news_articles", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.NewsArticleInstrument", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("Instrument")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("instrument");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.HasKey("ArticleId", "Instrument");

                    b.HasIndex("Instrument")
                        .HasDatabaseName("ix_news_article_instruments_instrument");

                    b.ToTable("news_article_instruments", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("PollingIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("polling_interval_minutes");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url_template");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_news_sources_enabled");

                    b.HasIndex("UrlTemplate")
                        .IsUnique()
                        .HasDatabaseName("ix_news_sources_url_unique");

                    b.ToTable("news_sources", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.PriceQuote", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Symbol", "Currency");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_price_quotes_fetched_at");

                    b.ToTable("price_quotes", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BrokerKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("broker_key");

                    b.Property<string>("BrokerReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broker_reference");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("FeesAmount")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("fees_amount");

                    b.Property<string>("FeesCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("fees_currency");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("instrument");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("instrument_name");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_currency");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(28, 8)")
                        .HasColumnName("quantity");

                    b.Property<short>("Side")
                        .HasColumnType("smallint")
                        .HasColumnName("side");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "BrokerKey", "BrokerReference")
                        .IsUnique()
                        .HasDatabaseName("ix_trades_broker_reference_unique")
                        .HasFilter("\"broker_reference\" IS NOT NULL");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.InvestmentDecision", b =>
                {
                    b.HasOne("Valyze.Infraestructure.EntityFramework.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valyze.Infraestructure.EntityFramework.Entities.Trade", null)
                        .WithMany()
                        .HasForeignKey("LinkedTradeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.NewsArticle", b =>
                {
                    b.HasOne("Valyze.Infraestructure.EntityFramework.Entities.NewsSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.NewsArticleInstrument", b =>
                {
                    b.HasOne("Valyze.Infraestructure.EntityFramework.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Valyze.Infraestructure.EntityFramework.Entities.Trade", b =>
                {
                    b.HasOne("Valyze.Infraestructure.EntityFramework.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
